[package]
name = "linear-algebra"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "linear-algebra-main"
path = "src/main.rs"

[dependencies]
thiserror = "1.0.63"
bewusstsein = { version = "0.1.0", path = "../../bewusstsein/rust", features = [ "memory" ] }